#!/bin/sh
. "$(dirname "$0")/../lib/AllrunPreamble.sh"

rm -rf 0
cp -r 0.orig 0

runApplication blockMesh
runApplication opticalRadiationFoam

# ----------------------------------------------------------------------------
