"""Bulk-region tet emitter (gmsh Python API).

Writes a Python script `bulk_body.py` into the workspace that, when run,
emits `bulk.msh` -- a tet volume mesh of the reactor body with one
cylindrical hole subtracted per lamp (at the lamp's annulus_outer_radius).
Physical Surfaces are emitted for each patch so `gmshToFoam` recovers
them as named boundaries.

The script is emitted as a standalone .py file rather than executed in
the calling process so the gmsh session is fully isolated (gmsh's global
state can interact badly across multiple `initialize()/finalize()` cycles
in long-lived processes).
"""
from __future__ import annotations

import os
from textwrap import dedent
from typing import List

from .geometry import Lamp, ReactorBody


def write_bulk_script(body: ReactorBody, lamps: List[Lamp], case_dir: str) -> None:
    """Write `<case_dir>/bulk_body.py` (the gmsh emitter for the bulk mesh).

    The emitted script:
      1. Builds the reactor body (box for v0.1; STL deferred).
      2. Cuts a cylindrical volume per lamp at radius
         `annulus_outer_radius`, padded slightly past each axis end so the
         boolean is robust to floating-point endpoint matching.
      3. Classifies the resulting surfaces into:
            <body.wall_patch_name>
            <body.endcap_lo_patch_name>, <body.endcap_hi_patch_name>
            <lamp.seam_patch_name (renamed to reactor_seam_lamp{i})>
            ... per lamp ...
      4. Adds a Distance + Threshold field around each seam so the bulk
         cells near the AMI match the annulus's circumferential spacing.
      5. Writes `bulk.msh` (msh2 format -- gmshToFoam can read it).

    Patch naming on the BULK side uses `reactor_seam_lamp{i}` to make the
    NCC fuse pair (lamp{i}_seam, reactor_seam_lamp{i}) unambiguous.
    """
    if body.box_min is None or body.box_max is None:
        raise NotImplementedError("Only box-bounded ReactorBody supported in v0.1")

    # Resolve seam refinement size: default to annulus circumferential spacing
    # 2*pi*r_seam / (4*nt_per_quad). Pick the tightest across lamps so the
    # seam-side weights line up. Bulk away from seams uses body.bulk_cell_size.
    seam_size = body.near_lamp_cell_size
    if seam_size is None:
        sizes = [
            2 * 3.141592653589793 * lamp.annulus_outer_radius
            / (4 * lamp.n_azimuth_per_quadrant)
            for lamp in lamps
        ]
        seam_size = min(sizes) if sizes else body.bulk_cell_size

    band = body.near_lamp_band_thickness
    if band is None:
        band = 2 * seam_size

    # Each lamp's cylindrical cut: axis as world-coord pair + radius + bulk
    # patch name. Pad by `pad` past each end so the cut robustly punches
    # through the body even when an endpoint sits exactly on a face.
    pad = 1e-3
    lamp_cuts = []
    for i, lamp in enumerate(lamps):
        lamp_cuts.append({
            "i": i,
            "axis_start": tuple(lamp.axis_start),
            "axis_end":   tuple(lamp.axis_end),
            "radius":     lamp.annulus_outer_radius,
            "pad":        pad,
            "seam_name":  f"reactor_seam_lamp{i}",
        })

    script = dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"Generated by uvmesh.bulk.write_bulk_script(); do not edit by hand.\"\"\"
        import math
        import os
        import sys

        import gmsh

        HERE = os.path.dirname(os.path.abspath(__file__))
        TOL  = 1e-6

        BOX_MIN = {tuple(body.box_min)!r}
        BOX_MAX = {tuple(body.box_max)!r}
        WALL_NAME      = {body.wall_patch_name!r}
        ENDCAP_LO_NAME = {body.endcap_lo_patch_name!r}
        ENDCAP_HI_NAME = {body.endcap_hi_patch_name!r}
        LAMP_CUTS = {lamp_cuts!r}
        SEAM_SIZE = {seam_size!r}
        BULK_SIZE = {body.bulk_cell_size!r}
        BAND      = {band!r}

        gmsh.initialize()
        gmsh.option.setNumber("General.Terminal", 0)
        gmsh.model.add("uvmesh-bulk")

        # Box body
        bx_min, by_min, bz_min = BOX_MIN
        bx_max, by_max, bz_max = BOX_MAX
        box = gmsh.model.occ.addBox(
            bx_min, by_min, bz_min,
            bx_max - bx_min, by_max - by_min, bz_max - bz_min,
        )
        body_dimtag = (3, box)

        # Cut each lamp's cylinder out of the body. Track lamp index per
        # axis so we can re-identify the seam surface afterwards.
        lamp_axes = []
        for cut in LAMP_CUTS:
            ax = cut["axis_start"]
            ay = cut["axis_end"]
            dx = ay[0] - ax[0]; dy = ay[1] - ax[1]; dz = ay[2] - ax[2]
            length = math.sqrt(dx*dx + dy*dy + dz*dz)
            ux = dx / length; uy = dy / length; uz = dz / length
            pad = cut["pad"]
            start = (ax[0] - pad * ux, ax[1] - pad * uy, ax[2] - pad * uz)
            extent = (
                dx + 2 * pad * ux,
                dy + 2 * pad * uy,
                dz + 2 * pad * uz,
            )
            cyl = gmsh.model.occ.addCylinder(
                start[0], start[1], start[2],
                extent[0], extent[1], extent[2],
                cut["radius"],
            )
            cut_result, _ = gmsh.model.occ.cut(
                [body_dimtag], [(3, cyl)], removeTool=True,
            )
            assert len(cut_result) == 1, (
                f"Lamp {{cut['i']}} cut produced {{len(cut_result)}} pieces; "
                "the lamp cylinder must lie entirely within the body."
            )
            body_dimtag = cut_result[0]
            lamp_axes.append((ax, ay, length, (ux, uy, uz), cut["radius"], cut["seam_name"]))

        gmsh.model.occ.synchronize()
        vol_tag = body_dimtag[1]

        # Classify each bounding surface.
        seam_groups = {{name: [] for _, _, _, _, _, name in lamp_axes}}
        wall_tags      = []
        endcap_lo_tags = []
        endcap_hi_tags = []

        for dim, tag in gmsh.model.getBoundary([(3, vol_tag)], oriented=False):
            if dim != 2:
                continue
            xmin, ymin, zmin, xmax, ymax, zmax = gmsh.model.getBoundingBox(dim, tag)
            cx, cy, cz = gmsh.model.occ.getCenterOfMass(dim, tag)

            # Endcap detection: flat in z at the box z extents.
            flat_z = abs(zmax - zmin) < TOL
            if flat_z and abs(zmin - bz_min) < TOL:
                endcap_lo_tags.append(tag); continue
            if flat_z and abs(zmin - bz_max) < TOL:
                endcap_hi_tags.append(tag); continue

            # Seam detection: surface centroid lies on a lamp axis within the
            # axis's parametric range. Distance from centroid to the line is
            # the perpendicular distance; the projection parameter `s` must
            # be in [0, length].
            seam_match = None
            for (ax, _ay, length, u, _radius, name) in lamp_axes:
                rx = cx - ax[0]; ry = cy - ax[1]; rz = cz - ax[2]
                s = rx*u[0] + ry*u[1] + rz*u[2]
                if not (-TOL <= s <= length + TOL):
                    continue
                # Perpendicular component
                px = rx - s*u[0]; py = ry - s*u[1]; pz = rz - s*u[2]
                d_perp = math.sqrt(px*px + py*py + pz*pz)
                if d_perp < TOL:
                    seam_match = name
                    break
            if seam_match is not None:
                seam_groups[seam_match].append(tag)
                continue

            wall_tags.append(tag)

        def add_physical(dim, tags, name):
            if not tags:
                return
            pg = gmsh.model.addPhysicalGroup(dim, tags)
            gmsh.model.setPhysicalName(dim, pg, name)
            print(f"  {{name:<40}} {{len(tags):>3}} surface(s) tags={{tags}}", file=sys.stderr)

        print("Physical groups:", file=sys.stderr)
        add_physical(2, wall_tags, WALL_NAME)
        add_physical(2, endcap_lo_tags, ENDCAP_LO_NAME)
        add_physical(2, endcap_hi_tags, ENDCAP_HI_NAME)
        for seam_name, seam_tags in seam_groups.items():
            add_physical(2, seam_tags, seam_name)
            if not seam_tags:
                raise RuntimeError(
                    f"Bulk classification failed: no surface classified as "
                    f"seam '{{seam_name}}'. Lamp axis may not intersect the body."
                )

        # Tag the volume as a Physical Group so gmsh exports the tet elements.
        # Without this, gmsh's default SaveAll=0 drops volume elements that
        # don't belong to any physical group and gmshToFoam reads zero cells.
        # The cellZone gmshToFoam builds from this group will be stale after
        # polyDualMesh (pre-dual cell indices); Allrun.mesh removes it.
        pg_vol = gmsh.model.addPhysicalGroup(3, [vol_tag])
        gmsh.model.setPhysicalName(3, pg_vol, "fluid")

        # Mesh sizing fields.
        all_seam_tags = [t for tags in seam_groups.values() for t in tags]
        if all_seam_tags:
            dist_f = gmsh.model.mesh.field.add("Distance")
            gmsh.model.mesh.field.setNumbers(dist_f, "SurfacesList", all_seam_tags)
            thr_f = gmsh.model.mesh.field.add("Threshold")
            gmsh.model.mesh.field.setNumber(thr_f, "InField", dist_f)
            gmsh.model.mesh.field.setNumber(thr_f, "SizeMin", SEAM_SIZE)
            gmsh.model.mesh.field.setNumber(thr_f, "SizeMax", BULK_SIZE)
            gmsh.model.mesh.field.setNumber(thr_f, "DistMin", 0.0)
            gmsh.model.mesh.field.setNumber(thr_f, "DistMax", BAND)
            gmsh.model.mesh.field.setAsBackgroundMesh(thr_f)

        gmsh.option.setNumber("Mesh.CharacteristicLengthMin", SEAM_SIZE)
        gmsh.option.setNumber("Mesh.CharacteristicLengthMax", BULK_SIZE)
        gmsh.option.setNumber("Mesh.MshFileVersion", 2.2)
        gmsh.model.mesh.generate(3)
        gmsh.write(os.path.join(HERE, "bulk.msh"))
        gmsh.finalize()
        print("Wrote", os.path.join(HERE, "bulk.msh"), file=sys.stderr)
        """)

    out_path = os.path.join(case_dir, "bulk_body.py")
    with open(out_path, "w") as fh:
        fh.write(script)
    os.chmod(out_path, 0o755)
