"""Case-writer + Allrun.mesh generator.

`build(case_dir, lamps, body)` writes the per-lamp annulus blockMeshDicts,
the bulk gmsh script, and an `Allrun.mesh` shell script that runs the full
meshing pipeline. The user's own Allrun is expected to invoke
`./_uvMesh/Allrun.mesh` (or its absolute path) before any solver step.

The combined mesh ends up at `<case_dir>/constant/polyMesh/`.
"""
from __future__ import annotations

import os
import stat
from typing import List

from .annulus import write_annulus_dict
from .bulk import write_bulk_script
from .geometry import Lamp, ReactorBody


_STUB_CONTROLDICT = """\
FoamFile { version 2.0; format ascii; class dictionary; object controlDict; }
application     none;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         1;
deltaT          1;
writeControl    timeStep;
writeInterval   1;
purgeWrite      0;
writeFormat     ascii;
writePrecision  6;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable false;
"""


def _write_stub_controldict(case_dir: str) -> None:
    os.makedirs(os.path.join(case_dir, "system"), exist_ok=True)
    with open(os.path.join(case_dir, "system", "controlDict"), "w") as fh:
        fh.write(_STUB_CONTROLDICT)


def _autoname_lamps(lamps: List[Lamp]) -> None:
    """Fill in patch names on lamps where the user left them blank."""
    for i, lamp in enumerate(lamps):
        if not lamp.sleeve_patch_name:
            lamp.sleeve_patch_name = f"lamp{i}_wall"
        if not lamp.seam_patch_name:
            lamp.seam_patch_name = f"lamp{i}_seam"
        # Flat end caps emit the *_endcap_{A,B} patch (wall); hemispherical
        # end caps emit *_tip_{A,B} instead (the curved lamp tip surface).
        # We auto-fill the relevant name based on the shape so the user
        # gets a sensible patch name in either case without having to set
        # all four explicitly.
        if lamp.endcap_a_shape == "flat" and not lamp.endcap_a_patch_name:
            lamp.endcap_a_patch_name = f"lamp{i}_endcap_A"
        if lamp.endcap_b_shape == "flat" and not lamp.endcap_b_patch_name:
            lamp.endcap_b_patch_name = f"lamp{i}_endcap_B"
        if lamp.endcap_a_shape == "hemisphere" and not lamp.tip_patch_name_a:
            lamp.tip_patch_name_a = f"lamp{i}_tip_A"
        if lamp.endcap_b_shape == "hemisphere" and not lamp.tip_patch_name_b:
            lamp.tip_patch_name_b = f"lamp{i}_tip_B"


def _fmt_vec(v) -> str:
    return f"({v[0]:.12g} {v[1]:.12g} {v[2]:.12g})"


def _write_allrun_mesh(case_dir: str, lamps: List[Lamp],
                       body: ReactorBody) -> None:
    """Generate the `_uvMesh/Allrun.mesh` driver script.

    The script is self-contained: assumes `WM_PROJECT_DIR` is set (OF env
    sourced). Runs blockMesh per lamp annulus + transformPoints to rotate
    the lamp-local annulus into world coords, gmsh + gmshToFoam +
    polyDualMesh for the bulk, drops the stale cellZone left behind by
    polyDualMesh, then mergeMeshes everything into <case>/constant/polyMesh
    and fuses each seam pair with createNonConformalCouples.

    A final checkMesh runs and the script exits 0 iff it reports "Mesh OK".
    """
    lines = []
    lines.append("#!/bin/sh")
    lines.append("# Generated by uvmesh.build(); do not edit by hand.")
    lines.append("# Re-run python3 mesh.py in the case directory to regenerate.")
    lines.append("set -e")
    lines.append('cd "$(dirname "$0")/.."')   # cd to case_dir
    lines.append('. "$WM_PROJECT_DIR/bin/tools/RunFunctions"')
    lines.append("")
    lines.append("# Clean any prior mesh.")
    lines.append("rm -rf constant/polyMesh")
    lines.append("")

    for i, lamp in enumerate(lamps):
        u = lamp.axis_unit()
        # OF v13's transformPoints takes a single string with comma-separated
        # transformations executed in the listed order. Rotate the lamp-local
        # +z axis onto the world-frame unit axis vector, then translate the
        # whole mesh so the (formerly z=0) axis_start sits at the world-frame
        # axis_start.
        rotate_token = f"rotate=({_fmt_vec((0,0,1))} {_fmt_vec(u)})"
        translate_token = f"translate={_fmt_vec(lamp.axis_start)}"
        lines.append(f"# Lamp {i}: {lamp.sleeve_patch_name}")
        lines.append(f"(")
        lines.append(f"    cd _uvMesh/annulus_lamp{i}")
        lines.append(f"    runApplication blockMesh")
        lines.append(
            f"    runApplication transformPoints "
            f"\"{rotate_token}, {translate_token}\""
        )
        lines.append(f")")
        lines.append("")

    # Bulk mesh
    if body.bulk_cells == "polyhedral":
        lines.append("# Bulk: gmsh tet -> polyDualMesh -> polyhedral cells.")
    else:
        lines.append("# Bulk: gmsh tet (kept as tets, polyDualMesh skipped --")
        lines.append("# see ReactorBody.bulk_cells docstring for the trade-off).")
    lines.append("(")
    lines.append("    cd _uvMesh")
    lines.append("    python3 bulk_body.py")
    lines.append(")")
    lines.append("(")
    lines.append("    cd _uvMesh/bulk_body")
    lines.append("    runApplication gmshToFoam ../bulk.msh")
    if body.bulk_cells == "polyhedral":
        lines.append("    runApplication polyDualMesh 90")
        # polyDualMesh leaves the cellZone built by gmshToFoam pointing at pre-
        # dual cell indices. Single-region bulks don't need it -- drop the file.
        lines.append("    rm -f constant/polyMesh/cellZones")
    # bulk_cells == "tet": gmshToFoam's output is the final bulk; the
    # cellZone it built is still valid (no dualization re-indexes) so
    # we leave it in place.
    lines.append(")")
    lines.append("")

    # Initialise the case's polyMesh from the bulk piece.
    lines.append("# Seed the case's polyMesh with the bulk piece.")
    lines.append("mkdir -p constant/polyMesh")
    lines.append("cp -r _uvMesh/bulk_body/constant/polyMesh/* constant/polyMesh/")
    lines.append("")

    # mergeMeshes all annulus subdirs into the case.
    annulus_paths = " ".join(
        f'"_uvMesh/annulus_lamp{i}"' for i in range(len(lamps))
    )
    lines.append("# Merge each lamp's O-grid annulus into the bulk.")
    lines.append(f"runApplication mergeMeshes -addCases '({annulus_paths})'")
    lines.append("")

    # createNonConformalCouples per lamp.
    lines.append("# Fuse each annulus seam to the corresponding bulk seam.")
    for i, lamp in enumerate(lamps):
        lines.append(
            f"runApplication -a createNonConformalCouples "
            f"reactor_seam_lamp{i} {lamp.seam_patch_name}"
        )
    lines.append("")

    # checkMesh
    lines.append("# Verify the final combined mesh. NCC-coupled meshes report")
    lines.append("# `Number of regions: 2 (or more)` -- this is normal, not an error.")
    lines.append("runApplication -a checkMesh")
    lines.append("")
    lines.append('echo "uvMesh: build complete -- constant/polyMesh ready."')
    lines.append("")

    out_path = os.path.join(case_dir, "_uvMesh", "Allrun.mesh")
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))
    os.chmod(out_path, os.stat(out_path).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def build(case_dir: str, lamps: List[Lamp], body: ReactorBody) -> None:
    """Write the meshing workspace and Allrun.mesh under `case_dir/_uvMesh/`.

    Existing `<case_dir>/_uvMesh/` is overwritten. The user's case configs
    under `<case_dir>/system/`, `<case_dir>/0/`, etc. are not touched.
    """
    if not lamps:
        raise ValueError("build(): at least one lamp is required")

    _autoname_lamps(lamps)

    ws = os.path.join(case_dir, "_uvMesh")
    os.makedirs(ws, exist_ok=True)

    # Per-lamp annulus subdirs.
    for i, lamp in enumerate(lamps):
        annulus_dir = os.path.join(ws, f"annulus_lamp{i}")
        # Pre-clean so a re-run produces a deterministic blockMeshDict tree.
        if os.path.exists(os.path.join(annulus_dir, "system", "blockMeshDict")):
            os.remove(os.path.join(annulus_dir, "system", "blockMeshDict"))
        write_annulus_dict(lamp, annulus_dir)
        _write_stub_controldict(annulus_dir)

    # Bulk: emitter script + scratch OF case for gmshToFoam.
    write_bulk_script(body, lamps, ws)
    bulk_case = os.path.join(ws, "bulk_body")
    _write_stub_controldict(bulk_case)

    # Top-level Allrun.mesh.
    _write_allrun_mesh(case_dir, lamps, body)
