#!/bin/sh
cd "${0%/*}" || exit 1

# Library
( cd src/opticalRadiationModels && wmake libso )

# Standalone solver
( cd applications/solvers/opticalRadiationFoam && wmake )

# Solver module (loaded by foamMultiRun for multi-region cases)
( cd applications/modules/opticalRadiation && wmake libso )
