#!/bin/sh
cd "${0%/*}" || exit 1

for case in */ ; do
    case_name="${case%/}"
    if [ -x "$case_name/Allclean" ]; then
        echo "==> cleaning $case_name"
        ( cd "$case_name" && ./Allclean )
    fi
done

# ----------------------------------------------------------------------------
