#!/bin/sh
cd "${0%/*}" || exit 1

# Regenerate STL geometry if missing
if [ ! -f constant/triSurface/bodyWall.stl ]; then
    python3 make_geometry.py
fi

blockMesh > log.blockMesh 2>&1
surfaceFeatures > log.surfaceFeatures 2>&1
snappyHexMesh -overwrite > log.snappyHexMesh 2>&1
checkMesh > log.checkMesh 2>&1
