#!/bin/sh
cd "${0%/*}" || exit 1

. "$(dirname "$0")/../lib/AllcleanCommon.sh"

# createNonConformalCouples writes topology changes into constant/fvMesh;
# cleanCase doesn't know about this directory.
rm -rf constant/fvMesh

# ----------------------------------------------------------------------------
