#!/bin/sh
cd "${0%/*}" || exit 1

. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

cleanCase
rm -rf postProcessing constant/polyMesh
rm -f system/blockMeshDict system/controlDict.flow.bak

# ----------------------------------------------------------------------------
