#!/bin/sh
. "$(dirname "$0")/../lib/AllrunPreamble.sh"

# Restore stock initial fields BEFORE createNonConformalCouples, which
# rewrites the seamL / seamR entries of every field for the coupling.
rm -rf 0
cp -r 0.orig 0

runApplication blockMesh
runApplication createNonConformalCouples -fields seamL seamR
runApplication foamPostProcess
